-- SELECT TOP 10
-- 	 B.PRODUTO
-- 	,A.DESCRICAO
-- 	,B.CENTRO_eSTOQUE
-- 	,B.ESTOQUE_SALDO
--     ,RANK() OVER(ORDER BY B.PRODUTO DESC) Rank
--   FROM PRODUTOS					A WITH(NOLOCK)
--   JOIN ESTOQUE_ATUAL 			B WITH(NOLOCK) ON B.PRODUTO = A.PRODUTO
--  WHERE B.CENTRO_ESTOQUE = 26
--  ORDER
--     BY B.ESTOQUE_SALDO DESC


    -- SELECT TOP 10
    --      B.PRODUTO              AS PRODUTO
    --     ,A.DESCRICAO            AS DESCRICAO
    --     ,COUNT(B.PRODUTO)       AS MOVIMENTACOES
    --   FROM PRODUTOS                 A WITH(NOLOCK)
    --   JOIN ESTOQUE_LANCAMENTOS      B WITH(NOLOCK)ON B.PRODUTO          = A.PRODUTO 
    --                                              AND B.TIPO_MOVIMENTO   = 1
    --                                              AND B.DATA BETWEEN '01/07/2022' AND '31/07/2022'
    -- GROUP BY 
    --          B.PRODUTO
    --         ,A.DESCRICAO
    --         ,A.PRODUTO
    -- ORDER BY COUNT(B.PRODUTO) DESC


SELECT DISTINCT
     A.PRODUTO              
    ,B.DESCRICAO
    ,SUM(A.QUANTIDADE)
    ,SUM(A.VENDA_BRUTA)
    ,SUM(A.DESCONTO)
    ,SUM(A.VENDA_LIQUIDA)
    --,A.DOCUMENTO_TIPO
  FROM VENDAS_ANALITICAS    A WITH(NOLOCK)
  JOIN PRODUTOS             B WITH(NOLOCK)ON B.PRODUTO  = A.PRODUTO

WHERE A.MOVIMENTO BETWEEN '01/08/2022' AND '30/08/2022'
  AND A.EMPRESA   = 26 

GROUP BY    
     A.PRODUTO
    ,B.DESCRICAO
    ,A.QUANTIDADE
    ,A.VENDA_BRUTA
    ,A.DESCONTO
    ,A.VENDA_LIQUIDA
    ,A.DOCUMENTO_TIPO

ORDER BY B.DESCRICAO

