SELECT
	*
  FROM
  (
	  SELECT
		 A.USUARIO		AS USUARIO
		,B.FORMULARIO	AS FORMULARIO
		,A.NOME			AS PERFIL
	  FROM USUARIOS						A WITH(NOLOCK)
		LEFT
		JOIN USUARIOS_FORMULARIOS		B WITH(NOLOCK)ON B.USUARIO = A.USUARIO
		LEFT
		JOIN USUARIOS_CONSULTAS			C WITH(NOLOCK)ON C.USUARIO = A.USUARIO
	 WHERE A.NOME  LIKE '%PERFIL%'
  )A
 PIVOT
	(MAX(FORMULARIO)  -- CAMPO ONDE CONTEM VALORES QUE SERÃO APLICADOS A COLUNA
		FOR PERFIL IN -- CAMPO ONDE CONTÉM NOME QUE CONVERTERÃO EM COLUNAS
		(			 
		 [PERFIL - FISCAL]
		,[PERFIL - CONTAS A PAGAR]
		,[PERFIL - COMPRAS]
		,[PERFIL - RECEBIMENTO]
		,[PERFIL - SEPARAÇÃO/ALOCAÇÃO/CHECKOUT]
		,[PERFIL - CONTAS RECEBER]
		,[PERFIL - CHECKOUT]
		,[PERFIL - SUPORTE ADMINISTRATIVO]
		,[PERFIL - DP]
		,[PERFIL - FINANCEIRO]
		,[PERFIL - GERENTE COMPRAS]
		,[PERFIL - ASSISTENTE PRECIFICAÇÃO]
		,[PERFIL - RECEBIMENTO APROVAÇÃO]
		,[PERFIL - FARMACEUTICO LIDER]
		,[PERFIL - LIDER]
		,[PERFIL - CONTAS A RECEBER LIDER]
		,[PERFIL - GERENTE (SANTIAGO)]
		,[PERFIL - GERENTE]
		,[PERFIL - GERENTE FARMACEUTICO]
		,[PERFIL - FARMACEUTICO]
		,[PERFIL - TESOURARIA CAIXA]
		,[PERFIL - DP ASSISTENTE]
		,[PERFIL - SNGPC]
		,[PERFIL - ADM DROGALESTE]
		,[PERFIL - INVENTÁRIO]
		,[PERFIL - CONFERENCIA CAIXA]
		,[PERFIL - INATIVOS]
		,[PERFIL - CONFERÊNCIA DE NOTAS]
		,[PERFIL - DIRETORIA]
		,[PERFIL - SUPERVISOR LOJAS]
		,[PERFIL - SUPORTE DESENVOLVIMENTO]
		,[PERFIL - CONTAS A PAGAR E CONFERENCIA CAIXAS
		,[PERFIL - ADMINISTRATIVO]
		,[PERFIL - ASSISTENTE QUALIDADE]
		,[PERFIL - SUPORTE TI]
		,[PERFIL - REGULATORIOS]
		,[PERFIL - CONTAS A PAGAR (MILTON)]
		,[PERFIL - CONSULTOR SAUDE E BELEZA]
		,[PERFIL - NOTAS]
		,[PERFIL - TRADE]
		,[PERFIL - MARKETING]
		,[PERFIL - DESENVOLVIMENTO]
		,[PERFIL - VALIDACAO PREMIACOES]
		,[PERFIL - TREINAMENTO SUPORTE]
		,[PERFIL - ASSISTENTE INVENTÁRIO]
		,[PERFIL - CONTAS A PAGAR LIDER]
		)
	)A