SELECT CASE 
			WHEN CONVERT(DATE,DATEADD(DAY, 1, :DATA_INICIAL)) >=  CONVERT(DATE,GETDATE())
			THEN CONVERT(DATE,GETDATE())
			ELSE
			CASE
				WHEN CONVERT(DATE,DATEADD(DAY, 6, :DATA_INICIAL)) > CONVERT(DATE,GETDATE())
				THEN CONVERT(DATE,GETDATE())
				ELSE CONVERT(DATE,DATEADD(DAY, 6, :DATA_INICIAL))
			END
        END             AS DATA_FINAL