DECLARE @ENTIDADE NUMERIC(15) =  :ENTIDADE

 SELECT 'Atenção: Só é permitidos entidades do perfil FARMACÊUTICO'
   FROM FUNCIONARIOS         A WITH(NOLOCK) 
   LEFT
   JOIN VENDEDORES           B WITH(NOLOCK)ON B.ENTIDADE        = A.ENTIDADE
   LEFT
   JOIN CARGOS_COMERCIAIS    C WITH(NOLOCK)ON C.CARGO_COMERCIAL = B.CARGO_COMERCIAL                                     
  WHERE (A.FUNCIONARIO     = @ENTIDADE)
    AND (C.CARGO_COMERCIAL IN(9, 11, 14) OR C.DESCRICAO IS NULL)