
/*====================================================================================================================*/
/* VERSÃO        DATA ALTERAÇÃO    ALTERADO POR            DESCRIÇÃO                                                  */
/*====================================================================================================================*/
/* 0001          21/10/2022        JUNIOR OLIVEIRA         INCLUSÃO DE VALIDAÇÃO QUE NÃO PERMITE LOJA DESTINO         */
/*                                                         DIFERENTE DO PASSO 1                                       */
/* 0002          19/10/2022        JUNIOR OLIVEIRA         INCLUSÃO DE VALIDAÇÃO QUE NÃO PERMITE GRAVAR PRODUTOS      */
/*                                                         QUE NÃO CONTÉM NO PASSO 1                                  */
/*====================================================================================================================*/

DECLARE @CONFERENCIA_TRANSFERENCIA       NUMERIC(15) = :CONFERENCIA_TRANSFERENCIA
DECLARE @ESTOQUE_TRANSFERENCIA           NUMERIC(15) = :ESTOQUE_TRANSFERENCIA 
DECLARE @TIPO_CONFERENCIA                NUMERIC(15) = :TIPO_CONFERENCIA
DECLARE @EMPRESA                         NUMERIC(15) = :EMPRESA
DECLARE @ENTIDADE                        NUMERIC(15) = :ENTIDADE

-- DECLARE @CONFERENCIA_TRANSFERENCIA       NUMERIC(15) = 107927
-- DECLARE @ESTOQUE_TRANSFERENCIA           NUMERIC(15) = 112588
-- DECLARE @TIPO_CONFERENCIA                NUMERIC(15) = 1
-- DECLARE @EMPRESA                         NUMERIC(15) = 7
-- DECLARE @ENTIDADE                        NUMERIC(15) = 10

 -------------------------------
 -- ATUALIZA NUMERO DO VOLUME --
 -------------------------------
UPDATE CONFERENCIAS_ESTOQUE_TRANF_VOLUME 
   SET VOLUME = B.VOLUME
  FROM CONFERENCIAS_ESTOQUE_TRANF_VOLUME A WITH(NOLOCK)
  JOIN (  SELECT A.CONFERENCIA_ESTOQUE_TRANF_VOLUME,
                 ROW_NUMBER() OVER(PARTITION BY A.CONFERENCIA_TRANSFERENCIA ORDER BY A.CONFERENCIA_ESTOQUE_TRANF_VOLUME) AS VOLUME
            FROM CONFERENCIAS_ESTOQUE_TRANF_VOLUME A WITH(NOLOCK)
           WHERE A.CONFERENCIA_TRANSFERENCIA = @CONFERENCIA_TRANSFERENCIA ) B ON A.CONFERENCIA_ESTOQUE_TRANF_VOLUME = B.CONFERENCIA_ESTOQUE_TRANF_VOLUME


SELECT TOP 1
       'Produto: ' + RTRIM(CAST(A.PRODUTO AS CHAR)) + 
       ' Lote: ' + A.LOTE +
       ' Validade: ' + ISNULL(A.VALIDADE_DIGITACAO,'') +
       ' Inválido.'
  FROM CONFERENCIAS_ESTOQUE_TRANF_MANUAL A WITH(NOLOCK)
  LEFT JOIN PRODUTOS_LOTE_VALIDADE       B WITH(NOLOCK) ON B.PRODUTO = A.PRODUTO
                                                       AND B.LOTE = A.LOTE
                                                       AND B.VALIDADE_DIGITACAO = A.VALIDADE_DIGITACAO
  LEFT JOIN PRODUTOS_FARMACIA            C WITH(NOLOCK) ON C.PRODUTO = A.PRODUTO
  LEFT JOIN PRODUTOS_RASTREABILIDADE     D WITH(NOLOCK) ON D.PRODUTO = A.PRODUTO
                                                       
 WHERE A.CONFERENCIA_TRANSFERENCIA = @CONFERENCIA_TRANSFERENCIA
   AND ((ISNULL(C.VENDA_CONTROLADA,'N') = 'S' AND GETDATE() BETWEEN ISNULL(C.DATA_INICIO_CONTROLADO, '01/01/1900') AND ISNULL(C.DATA_FINAL_CONTROLADO, DATEADD(DAY, 1, GETDATE())) ) 
    OR ISNULL(D.CONTROLE_RASTREABILIDADE,'N') = 'S')
   AND A.LOTE IS NOT NULL
   AND B.LOTE_VALIDADE IS NULL

UNION ALL

SELECT TOP 1 
       'Produto: ' + RTRIM(CAST(A.PRODUTO AS CHAR)) + 
       ' Lote: ' + A.LOTE +
       ' Validade: ' + A.VALIDADE_DIGITACAO +
       ' Inválido.'
  FROM CONFERENCIAS_ESTOQUE_TRANF_COLETA A WITH(NOLOCK)
  LEFT JOIN PRODUTOS_LOTE_VALIDADE       B WITH(NOLOCK) ON B.PRODUTO = A.PRODUTO
                                                       AND B.LOTE = A.LOTE
                                                       AND B.VALIDADE_DIGITACAO = A.VALIDADE_DIGITACAO
  LEFT JOIN PRODUTOS_FARMACIA            C WITH(NOLOCK) ON C.PRODUTO = A.PRODUTO
  LEFT JOIN PRODUTOS_RASTREABILIDADE     D WITH(NOLOCK) ON D.PRODUTO = A.PRODUTO

  WHERE A.CONFERENCIA_TRANSFERENCIA = @CONFERENCIA_TRANSFERENCIA
   AND ((ISNULL(C.VENDA_CONTROLADA,'N') = 'S' AND GETDATE() BETWEEN ISNULL(C.DATA_INICIO_CONTROLADO, '01/01/1900') AND ISNULL(C.DATA_FINAL_CONTROLADO, DATEADD(DAY, 1, GETDATE())) ) 
    OR ISNULL(D.CONTROLE_RASTREABILIDADE,'N') = 'S')
   AND A.LOTE IS NOT NULL
   AND B.LOTE_VALIDADE IS NULL

UNION ALL

SELECT 'Total de Quantidades Informadas Difere da Soma Conferida'
  FROM CONFERENCIAS_ESTOQUE_TRANF            A WITH(NOLOCK)
  JOIN ( SELECT SUM(A.QUANTIDADE_UNIT) AS QUNTIDADE_UNIT
          FROM CONFERENCIAS_ESTOQUE_TRANF_QUANTIDADES A WITH(NOLOCK)
         WHERE A.CONFERENCIA_TRANSFERENCIA = @CONFERENCIA_TRANSFERENCIA ) X ON 1 = 1 

LEFT JOIN ( SELECT SUM(A.QUANTIDADE) AS QUNTIDADE_VOLUMES
          FROM CONFERENCIAS_ESTOQUE_TRANF_VOLUME A WITH(NOLOCK)
         WHERE A.CONFERENCIA_TRANSFERENCIA = @CONFERENCIA_TRANSFERENCIA ) Z ON 1 = 1 

 WHERE A.CONFERENCIA_TRANSFERENCIA = @CONFERENCIA_TRANSFERENCIA
   AND X.QUNTIDADE_UNIT <> ISNULL(Z.QUNTIDADE_VOLUMES,0)

UNION ALL

SELECT 'Informe os Volumes'
  FROM CONFERENCIAS_ESTOQUE_TRANF            A WITH(NOLOCK)
LEFT JOIN ( SELECT SUM(A.VOLUME) AS VOLUME
          FROM CONFERENCIAS_ESTOQUE_TRANF_VOLUME A WITH(NOLOCK)
         WHERE A.CONFERENCIA_TRANSFERENCIA = @CONFERENCIA_TRANSFERENCIA ) Z ON 1 = 1 

 WHERE A.CONFERENCIA_TRANSFERENCIA = @CONFERENCIA_TRANSFERENCIA
   AND ISNULL(Z.VOLUME,0)= 0


UNION ALL

SELECT TOP 1 'Tipo de Conferência = Checkout. Não Permitido Lançar Dados na Ficha de Faltas'
  FROM CONFERENCIAS_ESTOQUE_TRANF         A WITH(NOLOCK)
  JOIN CONFERENCIAS_ESTOQUE_TRANF_FALTAS  B WITH(NOLOCK) ON B.CONFERENCIA_TRANSFERENCIA = A.CONFERENCIA_TRANSFERENCIA
  
 
 WHERE A.TIPO_CONFERENCIA = 1
   AND A.CONFERENCIA_TRANSFERENCIA =@CONFERENCIA_TRANSFERENCIA
   
UNION ALL

SELECT TOP 1 'Tipo de Conferência = Digitação. Não Permitido Lançar Dados na Ficha Coleta'
  FROM CONFERENCIAS_ESTOQUE_TRANF         A WITH(NOLOCK)
  JOIN CONFERENCIAS_ESTOQUE_TRANF_COLETA  B WITH(NOLOCK) ON B.CONFERENCIA_TRANSFERENCIA = A.CONFERENCIA_TRANSFERENCIA
  
 
 WHERE A.TIPO_CONFERENCIA          = 2
   AND A.CONFERENCIA_TRANSFERENCIA = @CONFERENCIA_TRANSFERENCIA
   
UNION ALL

SELECT TOP 1 'Tipo de Conferência = Digitação. Não Permitido Lançar Dados na Ficha Conf.Manual'
  FROM CONFERENCIAS_ESTOQUE_TRANF         A WITH(NOLOCK)
  JOIN CONFERENCIAS_ESTOQUE_TRANF_MANUAL  B WITH(NOLOCK) ON B.CONFERENCIA_TRANSFERENCIA = A.CONFERENCIA_TRANSFERENCIA  
 
 WHERE A.TIPO_CONFERENCIA          = 2
   AND A.CONFERENCIA_TRANSFERENCIA = @CONFERENCIA_TRANSFERENCIA      

UNION ALL

SELECT 'Produto ' + CAST(D.PRODUTO AS VARCHAR(30)) + ' - ' + D.DESCRICAO + ' Exige Checkout'
  FROM ESTOQUE_TRANSFERENCIAS          A WITH(NOLOCK)
  JOIN ESTOQUE_TRANSFERENCIAS_PRODUTOS B WITH(NOLOCK) ON B.ESTOQUE_TRANSFERENCIA = A.ESTOQUE_TRANSFERENCIA
  JOIN PRODUTOS_FARMACIA               C WITH(NOLOCK) ON C.PRODUTO               = B.PRODUTO
                                                     AND C.VENDA_CONTROLADA      = 'S' 
													 AND A.MOVIMENTO BETWEEN ISNULL(C.DATA_INICIO_CONTROLADO, '01/01/1900') AND ISNULL(C.DATA_FINAL_CONTROLADO, DATEADD(DAY, 1, A.MOVIMENTO)) 
  JOIN PRODUTOS                        D WITH(NOLOCK) ON D.PRODUTO               = B.PRODUTO
  
 WHERE A.ESTOQUE_TRANSFERENCIA = @ESTOQUE_TRANSFERENCIA
   AND @TIPO_CONFERENCIA <> 1 --CHECKOUT--

   
UNION ALL   

SELECT 'Produto :'+CAST(D.DESCRICAO AS VARCHAR(40))+' obrigatório informar  Lote / Validade'
       FROM CONFERENCIAS_ESTOQUE_TRANF         A WITH(NOLOCK)
       JOIN CONFERENCIAS_ESTOQUE_TRANF_COLETA  B WITH(NOLOCK) ON A.CONFERENCIA_TRANSFERENCIA = B.CONFERENCIA_TRANSFERENCIA
       JOIN PRODUTOS_FARMACIA                  C WITH(NOLOCK) ON C.PRODUTO   = B.PRODUTO
       JOIN PRODUTOS                           D WITH(NOLOCK) ON D.PRODUTO = B.PRODUTO
       JOIN PARAMETROS_ESTOQUE                 F WITH(NOLOCK) ON A.EMPRESA = F.EMPRESA_USUARIA 
       WHERE A.CONFERENCIA_TRANSFERENCIA = @CONFERENCIA_TRANSFERENCIA
       AND ( ISNULL(C.VENDA_CONTROLADA , 'N' )= 'S' )
	   AND GETDATE() BETWEEN ISNULL(C.DATA_INICIO_CONTROLADO, '01/01/1900') AND ISNULL(C.DATA_FINAL_CONTROLADO, DATEADD(DAY, 1, GETDATE())) 
       AND (B.LOTE IS NULL OR B.VALIDADE_DIGITACAO IS NULL)

UNION ALL   

SELECT 'Produto :'+CAST(D.DESCRICAO AS VARCHAR(40))+' obrigatório informar  Lote / Validade'
       FROM CONFERENCIAS_ESTOQUE_TRANF         A WITH(NOLOCK)
       JOIN CONFERENCIAS_ESTOQUE_TRANF_MANUAL  B WITH(NOLOCK) ON A.CONFERENCIA_TRANSFERENCIA = B.CONFERENCIA_TRANSFERENCIA
       JOIN PRODUTOS_FARMACIA                  C WITH(NOLOCK) ON C.PRODUTO   = B.PRODUTO
       JOIN PRODUTOS                           D WITH(NOLOCK) ON D.PRODUTO = B.PRODUTO
       JOIN PARAMETROS_ESTOQUE                 F WITH(NOLOCK) ON A.EMPRESA = F.EMPRESA_USUARIA 
       WHERE A.CONFERENCIA_TRANSFERENCIA = @CONFERENCIA_TRANSFERENCIA
       AND ( ISNULL(C.VENDA_CONTROLADA , 'N' )= 'S' )
	   AND GETDATE() BETWEEN ISNULL(C.DATA_INICIO_CONTROLADO, '01/01/1900') AND ISNULL(C.DATA_FINAL_CONTROLADO, DATEADD(DAY, 1, GETDATE())) 
       AND (B.LOTE IS NULL OR B.VALIDADE_DIGITACAO IS NULL)

UNION ALL

SELECT 'FAVOR PREENCHER A GUIA - F1 (Conf-Manual)!'
      FROM CONFERENCIAS_ESTOQUE_TRANF        A WITH(NOLOCK)
 LEFT JOIN CONFERENCIAS_ESTOQUE_TRANF_MANUAL B WITH(NOLOCK) ON B.CONFERENCIA_TRANSFERENCIA = A.CONFERENCIA_TRANSFERENCIA
  
 WHERE A.CONFERENCIA_TRANSFERENCIA = @CONFERENCIA_TRANSFERENCIA
   AND B.CONFERENCIA_TRANSFERENCIA IS NULL


/*==========================================================================================*/
/*                   NÃO PERMITE LOJA DESTINDO DIFERENTE DO PASSO 1                         */
/*==========================================================================================*/

UNION ALL 

SELECT TOP 1 CONCAT('A empresa destino(Passo 2) difere da empresa destino(Passo 1)', CHAR(13)+CHAR(10)+CHAR(13)+CHAR(10), 'Empresa Destino(Passo 1): ', A.ENTIDADE, CHAR(13)+CHAR(10), 'Empresa Destino(Passo 2): ', @ENTIDADE) 
  FROM ESTOQUE_TRANSFERENCIAS    A WITH(NOLOCK)
 WHERE 1=1
   AND A.ESTOQUE_TRANSFERENCIA = @ESTOQUE_TRANSFERENCIA
   AND A.EMPRESA               = @EMPRESA
   AND A.ENTIDADE             <> @ENTIDADE
   

   
/*==========================================================================================*/
/*              CONFERE SE PRODUTOS NO PASSO 2 SÃO SOLICITADOS NO PASSO 1                   */
/*==========================================================================================*/

UNION ALL 

SELECT 'Os produtos lançados não conferem com os produtos do Passo 1'
WHERE EXISTS
  (
        SELECT
              PRODUTO
              ,CODIGO_BARRAS
              ,A.ESTOQUE_TRANSFERENCIA
          FROM CONFERENCIAS_ESTOQUE_TRANF           A WITH(NOLOCK)
          LEFT
          JOIN CONFERENCIAS_ESTOQUE_TRANF_MANUAL    B WITH(NOLOCK)ON B.CONFERENCIA_TRANSFERENCIA = A.CONFERENCIA_TRANSFERENCIA

        WHERE A.ESTOQUE_TRANSFERENCIA = @ESTOQUE_TRANSFERENCIA

        EXCEPT

        SELECT
               B.PRODUTO
              ,B.CODIGO_BARRA
              ,A.ESTOQUE_TRANSFERENCIA
          FROM ESTOQUE_TRANSFERENCIAS             A WITH(NOLOCK)
          LEFT
          JOIN ESTOQUE_TRANSFERENCIAS_PRODUTOS    B WITH(NOLOCK)ON A.ESTOQUE_TRANSFERENCIA = B.ESTOQUE_TRANSFERENCIA
        WHERE A.ESTOQUE_TRANSFERENCIA = @ESTOQUE_TRANSFERENCIA
 ) 

